[package]
name = "rust_multibackend_app"
version = "0.1.1"
edition = "2021"

# wasm-bindgen縺後Λ繧､繝悶Λ繝ｪ縺ｨ縺励※繧ｯ繝ｬ繝ｼ繝医ｒ繧ｳ繝ｳ繝代う繝ｫ縺吶ｋ縺溘ａ縺ｫ蠢・ｦ・
[lib]
crate-type = ["cdylib", "rlib"]

[features]
# 繝・ヵ繧ｩ繝ｫ繝医〒gui feature繧呈怏蜉ｹ縺ｫ縺吶ｋ
default = []
# gui feature縺梧怏蜉ｹ縺ｪ蝣ｴ蜷医↓縲［inifb縲〉aw-window-handle縲『inapi繧呈怏蜉ｹ縺ｫ縺吶ｋ
gui = [
    "dep:winit",
    "dep:pixels",
]
gui-file = [
    "gui",
    "dep:rfd",              # 繝阪う繝・ぅ繝悶ヵ繧｡繧､繝ｫ繝繧､繧｢繝ｭ繧ｰ
]
tui = ["dep:crossterm"]
wasm = [
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "dep:web-sys",
    "dep:console_error_panic_hook",
    "getrandom/js"
]
uefi = ["dep:uefi", "dep:log", "dep:core_maths"]
mobile = ["dep:slint"]

[dependencies]
ab_glyph = { version = "0.2.31", default-features = false, features = ["libm"] }
slint = { version = "1", optional = true }
phf = { version = "0.13", features = ["macros"], default-features = false }

# 繝舌ャ繧ｯ繧ｨ繝ｳ繝峨＃縺ｨ縺ｮ繧ｪ繝励す繝ｧ繝翫Ν縺ｪ萓晏ｭ倬未菫・
rfd = { version = "0.15", optional = true, default-features = false, features = ["xdg-portal", "async-std"] }
crossterm = { version = "0.29.0", optional = true }
core_maths = { version = "0.1.1", optional = true }


# GUI backend
winit = { version = "0.28", optional = true, default-features = false, features = ["x11"] }
pixels = { version = "0.14", optional = true }


# WASM逕ｨ縺ｮ繧ｪ繝励す繝ｧ繝翫Ν縺ｪ萓晏ｭ倬未菫・
wasm-bindgen = { version = "0.2.87", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
getrandom = { version = "0.2", optional = true, features = ["js"] }

# UEFI逕ｨ縺ｮ繧ｪ繝励す繝ｧ繝翫Ν縺ｪ萓晏ｭ倬未菫・
uefi = { version = "0.35.0", optional = true, features = ["alloc", "panic_handler", "logger" ] }
log = { version = "0.4", optional = true }

[dependencies.web-sys]
version = "0.3.64"
optional = true
features = [
    'Document',
    'Window',
    'Element',
    'HtmlCanvasElement',
    'HtmlInputElement',
    'InputEvent',
    'CanvasRenderingContext2d',
    'ImageData',
    'Blob',
    'Url',
    'KeyboardEvent',
    'WebSocket',
    'ErrorEvent',
    'CloseEvent',
    'console',
    'FileReader',
    'ProgressEvent',
    'File',
    'FileList',
    'Storage',
    'EventTarget',
    'HtmlElement',
    'CssStyleDeclaration',
    'PointerEvent',
    'WheelEvent',
    'AddEventListenerOptions',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
]


# UEFI繧ｿ繝ｼ繧ｲ繝・ヨ逕ｨ縺ｮ繝ｪ繝ｪ繝ｼ繧ｹ繝励Ο繝輔ぃ繧､繝ｫ險ｭ螳・
# 繝代ル繝・け縺励◆髫帙↓繧ｹ繧ｿ繝・け繧貞ｷｻ縺肴綾縺吶・縺ｧ縺ｯ縺ｪ縺上∝叉蠎ｧ縺ｫ蛛懈ｭ｢縺輔○繧・
[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"


[build-dependencies]
slint-build = { version = "1" }

# WASM繧ｿ繝ｼ繧ｲ繝・ヨ縺ｮ繝薙Ν繝画凾縺ｫ縺ｮ縺ｿ蠢・ｦ√→縺ｪ繧倶ｾ晏ｭ倬未菫・
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
